image: nixos/latest
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
sources:
  - https://git.sr.ht/~dannypsnl/violet
tasks:
  - install-elan: |
      nix-env -iA nixos.elan
  - setup-toolchain: |
      elan default stable
  - build: |
      cd violet
      lake update
      lake build
  - test: |
      cd violet
      lake exe lspec
