name: Build
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v2
      id: nix-cache
      with:
        path: /tmp/nix-store
        key: ${{ runner.os }}-nix-store

    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: "import nix store"
      if: "steps.nix-cache.outputs.cache-hit == 'true'"
      run: nix-store --import < /tmp/nix-store

    - run: nix flake check
    - run: nix build .

    - name: "export nix store"
      run: nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nix-store
