name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: |
          ./llvm
      key: llvm-14
    - uses: KyleMayes/install-llvm-action@v1
      with:
        version: "14.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - uses: actions/checkout@v3
    - name: Build
      run: |
        export LLVM_SYS_140_PREFIX=$(./llvm/bin/llvm-config --prefix)
        cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
